import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
// import Nav from "../components/navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import MathContextProvider from "../context/MathContextProvider";
import Header from "../components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MathContextProvider>
          <SessionProvider>
            <NextUIProvider>
              {/* <Nav /> */}
              <Header />
              <div className="container mx-auto px-4 max-w-6xl">{children}</div>
            </NextUIProvider>
          </SessionProvider>
        </MathContextProvider>
      </body>
    </html>
  );
}
